/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Pso */

#ifndef _Included_Pso
#define _Included_Pso
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Pso
 * Method:    algorithmStart
 * Signature: ([I[I[I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_Pso_algorithmStart
  (JNIEnv *, jobject, jintArray, jintArray, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
